select * from TABLE(KMEANSCOLORUDF(2,'CPU'));
select * from TABLE(KMEANSCOLORUDF(2,'GPU'));

--#BGBLK 3
select * from TABLE(KMEANSCOLORUDF(2,'CPU'));
--#EOBLK
--#BGBLK 3
select * from TABLE(KMEANSCOLORUDF(4,'CPU'));
--#EOBLK
--#BGBLK 3
select * from TABLE(KMEANSCOLORUDF(8,'CPU'));
--#EOBLK
--#BGBLK 3
select * from TABLE(KMEANSCOLORUDF(16,'CPU'));
--#EOBLK

--#BGBLK 3
select * from TABLE(KMEANSCOLORUDF(2,'GPU'));
--#EOBLK
--#BGBLK 3
select * from TABLE(KMEANSCOLORUDF(4,'GPU'));
--#EOBLK
--#BGBLK 3
select * from TABLE(KMEANSCOLORUDF(8,'GPU'));
--#EOBLK
--#BGBLK 3
select * from TABLE(KMEANSCOLORUDF(16,'GPU'));
--#EOBLK

