db2 connect to kmeans

db2 "DROP Function KMEANSCOLORUDF"

db2 "CREATE FUNCTION KMEANSCOLORUDF(NUMCLUSTERS SMALLINT, DEVICE CHAR(3), TABLE_NAME VARCHAR(255))
RETURNS TABLE(C1 DOUBLE, C2 DOUBLE, C3 DOUBLE, C4 DOUBLE, C5 DOUBLE, C6 DOUBLE, C7 DOUBLE, C8 DOUBLE, C9 DOUBLE)
EXTERNAL NAME 'cudaudfsrv!kmeansColorUDF'
DETERMINISTIC
NO EXTERNAL ACTION
FENCED
NOT NULL CALL
LANGUAGE C
PARAMETER STYLE DB2SQL
SCRATCHPAD
FINAL CALL
DISALLOW PARALLEL
DBINFO"

db2 "DROP Function KMEANSCOLORSTATICUDF"

db2 "CREATE FUNCTION KMEANSCOLORSTATICUDF(NUMCLUSTERS SMALLINT, DEVICE CHAR(3))
RETURNS TABLE(C1 DOUBLE, C2 DOUBLE, C3 DOUBLE, C4 DOUBLE, C5 DOUBLE, C6 DOUBLE, C7 DOUBLE, C8 DOUBLE, C9 DOUBLE)
EXTERNAL NAME 'cudaudfsrv!kmeansColorStaticUDF'
DETERMINISTIC
NO EXTERNAL ACTION
FENCED
NOT NULL CALL
LANGUAGE C
PARAMETER STYLE DB2SQL
SCRATCHPAD
FINAL CALL
DISALLOW PARALLEL
DBINFO"
